// import pptxgen from "pptxgenjs";

// const COLORS = {
//     primary: "2563EB",
//     secondary: "0F172A",
//     text: "334155",
//     light: "F8FAFC",
//     border: "E2E8F0",
//     white: "FFFFFF",
//     muted: "64748B",
// };

// export const generatePpt = async (data) => {
//     try {
//         const ppt = new pptxgen();
//         ppt.layout = "LAYOUT_WIDE";
//         ppt.author = "CortexAI";
//         ppt.title = data.title;
//         ppt.subject = data.title;
//         ppt.company = "CortexAI";
//         ppt.theme = {
//             headFontFace: "Aptos",
//             bodyFontFace: "Aptos",
//         };
//         addCover(ppt, data);
//         data?.slides?.forEach((s, i) => {
//             addContentSlide(ppt, s.title, s.points, i + 1, data.slides.length);
//         });
//         addThankYou(ppt);
//         return ppt;
//     } catch (error) {
//         console.log(error);
//     }
// };

// const addCover = (ppt, data) => {
//     const slide = ppt.addSlide();
//     slide.background = {
//         color: COLORS.primary,
//     };
//     slide.addShape(ppt.ShapeType.rect, {
//         x: 0,
//         y: 0,
//         w: 13.33,
//         h: 0.18,
//         fill: {
//             color: "60A5FA",
//         },
//         line: {
//             color: "60A5FA",
//         },
//     });
//     slide.addText(data.title, {
//         x: 0.7,
//         y: 1.7,
//         w: 12,
//         h: 0.8,
//         align: "center",
//         color: COLORS.white,
//         bold: true,
//         fontSize: 28,
//     });
//     slide.addText(data.subtitle, {
//         x: 1,
//         y: 2.8,
//         w: 11.5,
//         h: 0.4,
//         align: "center",
//         color: "DBEAFE",
//         fontSize: 15,
//     });
//     slide.addText("Generated By CortexAI", {
//         x: 0,
//         y: 6.9,
//         w: 13.33,
//         h: 0.2,
//         align: "center",
//         color: "BFDBFE",
//         fontSize: 10,
//     });
// };

// const addContentSlide = (ppt, title, points, page, total) => {
//     const slide = ppt.addSlide();
//     slide.background = {
//         color: COLORS.white,
//     };
//     slide.addText(title, {
//         x: 0.6,
//         y: 0.35,
//         w: 10,
//         h: 0.4,
//         color: COLORS.primary,
//         bold: true,
//         fontSize: 24,
//     });
//     slide.addShape(ppt.ShapeType.line, {
//         x: 0.6,
//         y: 0.85,
//         w: 12,
//         h: 0,
//         line: {
//             color: COLORS.border,
//             width: 1.2,
//         },
//     });
//     const visiblePoints = points.slice(0, 6);
//     visiblePoints?.forEach((p, i) => {
//         const y = 1.2 + i * 0.75;
//         slide.addShape(ppt.ShapeType.roundRect, {
//             x: 0.7,
//             y,
//             w: 12,
//             h: 0.58,
//             line: {
//                 color: COLORS.border,
//             },
//             fill: {
//                 color: i % 2 ? "F8FAFC" : "EFF6FF",
//             },
//             radius: 0.08,
//         });
//         slide.addShape(ppt.ShapeType.ellipse, {
//             x: 0.92,
//             y: y + 0.18,
//             w: 0.12,
//             h: 0.12,
//             fill: {
//                 color: COLORS.primary,
//             },
//             line: {
//                 color: COLORS.primary,
//             },
//         });
//         slide.addText(p, {
//             x: 1.2,
//             y: y + 0.08,
//             w: 11,
//             h: 0.35,
//             color: COLORS.text,
//             fit: "shrink",
//             fontSize: 15,
//         });
//         slide.addText(`${page}/${total}`, {
//             x: 12.1,
//             y: 6.9,
//             w: 0.8,
//             h: 0.2,
//             color: COLORS.muted,
//             align: "right",
//             fontSize: 10,
//         });
//         slide.addText("CortexAi", {
//             x: 0.6,
//             y: 6.9,
//             w: 2,
//             h: 0.2,
//             color: COLORS.muted,
//             fontSize: 10,
//         });
//     });
// };

// const addThankYou = (ppt) => {
//     const slide = ppt.addSlide();
//     slide.background = {
//         color: COLORS.secondary,
//     };
//     slide.addText("Thank You", {
//         x: 0,
//         y: 0.2,
//         w: 13.33,
//         h: 0.8,
//         align: "center",
//         color: COLORS.white,
//         bold: true,
//         fontSize: 34,
//     });
//     slide.addText("Generated By CortexAI", {
//         x: 0,
//         y: 6.9,
//         w: 13.33,
//         h: 0.2,
//         align: "center",
//         color: "94A3B8",
//         fontSize: 10,
//     });
// };

import pptxgen from "pptxgenjs";

const COLORS = {
    primary: "2563EB",
    secondary: "0F172A",
    text: "334155",
    light: "F8FAFC",
    border: "E2E8F0",
    white: "FFFFFF",
    muted: "64748B",
    accent: "60A5FA",
};

export const generatePpt = async (data) => {
    try {
        const ppt = new pptxgen();

        ppt.layout = "LAYOUT_WIDE";
        ppt.author = "CortexAI";
        ppt.company = "CortexAI";
        ppt.subject = data.title;
        ppt.title = data.title;

        ppt.theme = {
            headFontFace: "Aptos Display",
            bodyFontFace: "Aptos",
            lang: "en-US",
        };

        addCover(ppt, data);

        data?.slides?.forEach((slideData, index) => {
            addContentSlide(
                ppt,
                slideData.title,
                slideData.points || [],
                index + 1,
                data.slides.length,
            );
        });

        addThankYou(ppt);

        return ppt;
    } catch (error) {
        console.error("PPT Generation Error:", error);
        throw error;
    }
};

const addCover = (ppt, data) => {
    const slide = ppt.addSlide();

    slide.background = {
        color: COLORS.secondary,
    };

    // Top accent line
    slide.addShape(ppt.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 13.33,
        h: 0.12,
        fill: { color: COLORS.accent },
        line: { color: COLORS.accent },
    });

    // Decorative circles
    slide.addShape(ppt.ShapeType.ellipse, {
        x: 10.5,
        y: -0.8,
        w: 3.5,
        h: 3.5,
        fill: {
            color: COLORS.accent,
            transparency: 75,
        },
        line: {
            color: COLORS.accent,
            transparency: 100,
        },
    });

    slide.addShape(ppt.ShapeType.ellipse, {
        x: -1,
        y: 5,
        w: 3,
        h: 3,
        fill: {
            color: COLORS.primary,
            transparency: 65,
        },
        line: {
            color: COLORS.primary,
            transparency: 100,
        },
    });

    slide.addText(data.title || "Presentation Title", {
        x: 0.8,
        y: 2,
        w: 11.8,
        h: 0.8,
        align: "center",
        color: COLORS.white,
        bold: true,
        fontSize: 28,
    });

    slide.addText(data.subtitle || "", {
        x: 1,
        y: 3,
        w: 11.5,
        h: 0.4,
        align: "center",
        color: "CBD5E1",
        fontSize: 15,
    });

    slide.addText("Generated by CortexAI", {
        x: 0,
        y: 6.9,
        w: 13.33,
        h: 0.2,
        align: "center",
        color: "94A3B8",
        fontSize: 10,
    });
};

const addContentSlide = (ppt, title, points, page, total) => {
    const slide = ppt.addSlide();

    slide.background = {
        color: COLORS.white,
    };

    // Left Accent Bar
    slide.addShape(ppt.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 0.15,
        h: 0.95,
        fill: { color: COLORS.primary },
        line: { color: COLORS.primary },
    });

    // Title
    slide.addText(title, {
        x: 0.35,
        y: 0.25,
        w: 10,
        h: 0.45,
        color: COLORS.secondary,
        bold: true,
        fontSize: 24,
    });

    // Divider
    slide.addShape(ppt.ShapeType.line, {
        x: 0.35,
        y: 0.9,
        w: 12.3,
        h: 0,
        line: {
            color: COLORS.border,
            width: 1,
        },
    });

    const visiblePoints = points.slice(0, 6);

    visiblePoints.forEach((point, index) => {
        const y = 1.25 + index * 0.8;

        // Card
        slide.addShape(ppt.ShapeType.roundRect, {
            x: 0.6,
            y,
            w: 12,
            h: 0.62,
            fill: {
                color: index % 2 === 0 ? "FFFFFF" : "F8FAFC",
            },
            line: {
                color: COLORS.border,
                width: 1,
            },
        });

        // Number Circle
        slide.addShape(ppt.ShapeType.ellipse, {
            x: 0.85,
            y: y + 0.14,
            w: 0.22,
            h: 0.22,
            fill: {
                color: COLORS.primary,
            },
            line: {
                color: COLORS.primary,
            },
        });

        slide.addText(String(index + 1), {
            x: 0.88,
            y: y + 0.12,
            w: 0.16,
            h: 0.16,
            fontSize: 8,
            bold: true,
            color: COLORS.white,
            align: "center",
        });

        slide.addText(point, {
            x: 1.25,
            y: y + 0.08,
            w: 10.8,
            h: 0.35,
            color: COLORS.text,
            fontSize: 15,
            fit: "shrink",
        });
    });

    // Footer
    slide.addShape(ppt.ShapeType.line, {
        x: 0.4,
        y: 6.75,
        w: 12.3,
        h: 0,
        line: {
            color: COLORS.border,
            width: 1,
        },
    });

    slide.addText("CortexAI", {
        x: 0.5,
        y: 6.9,
        w: 2,
        h: 0.2,
        color: COLORS.muted,
        fontSize: 10,
    });

    slide.addText(`Slide ${page} of ${total}`, {
        x: 10.8,
        y: 6.9,
        w: 1.8,
        h: 0.2,
        color: COLORS.muted,
        align: "right",
        fontSize: 10,
    });
};

const addThankYou = (ppt) => {
    const slide = ppt.addSlide();

    slide.background = {
        color: COLORS.secondary,
    };

    slide.addShape(ppt.ShapeType.ellipse, {
        x: 4.7,
        y: 1.3,
        w: 4,
        h: 4,
        fill: {
            color: COLORS.primary,
            transparency: 80,
        },
        line: {
            color: COLORS.primary,
            transparency: 100,
        },
    });

    slide.addText("Thank You", {
        x: 0,
        y: 2.8,
        w: 13.33,
        h: 0.8,
        align: "center",
        color: COLORS.white,
        bold: true,
        fontSize: 34,
    });

    slide.addText("Questions & Discussion", {
        x: 0,
        y: 3.7,
        w: 13.33,
        h: 0.3,
        align: "center",
        color: "CBD5E1",
        fontSize: 16,
    });

    slide.addText("Generated by CortexAI", {
        x: 0,
        y: 6.9,
        w: 13.33,
        h: 0.2,
        align: "center",
        color: "94A3B8",
        fontSize: 10,
    });
};